#!/usr/bin/env bash


if [[ $1 =~ "join:" ]]; then
    EMAIL=`echo $1 | sed s/join://`
    echo asking to join $PWD
    #create token data and a token
    echo ${EMAIL} | token data ${EMAIL}
    TOKEN=`token create ${EMAIL}`
    echo -e "email: ${EMAIL}\ntoken: ${TOKEN}" \
      | render "${ROOT}/messages/welcome.handlebars" \
      | send --markdown ses
    #error out, this isn't a login
    exit 1
else
    USER=$(token decode $1)
    SUCCESS=$?
    if [ $SUCCESS -eq 0 ]; then
        USER_HOME="${USER_ROOT}/${USER}"
        if [ ! -d "${USER_HOME}" ]; then
            mkdir -p "${USER_HOME}"
        fi
        touch "${USER_HOME}/last_login"
        echo $USER
    else
        exit $SUCCESS
    fi
fi

